"""add_public_access_token

Revision ID: 01a106cf9979
Revises: d9a20e585829
Create Date: 2026-07-16 10:45:27.231607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a106cf9979'
down_revision: Union[str, None] = 'd9a20e585829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('public_access_token', sa.Uuid(), nullable=True))
    op.execute("UPDATE bills SET public_access_token = gen_random_uuid() WHERE public_access_token IS NULL")
    op.create_index(op.f('ix_bills_public_access_token'), 'bills', ['public_access_token'], unique=True)
    op.add_column('products', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('quantity_in_stock', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('products', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.drop_column('products', 'is_deleted')
    op.drop_column('products', 'updated_by')
    op.drop_column('products', 'created_by')
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'quantity_in_stock')
    op.drop_column('products', 'type')
    op.drop_index(op.f('ix_bills_public_access_token'), table_name='bills')
    op.drop_column('bills', 'public_access_token')
    # ### end Alembic commands ###
