"""add_public_access_token

Revision ID: 01a106cf9979
Revises: d9a20e585829
Create Date: 2026-07-16 10:45:27.231607

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '01a106cf9979'
down_revision: str | None = 'd9a20e585829'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _column_exists(table: str, column: str) -> bool:
    """Check if a column already exists in a table."""
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            "SELECT 1 FROM information_schema.columns "
            "WHERE table_name = :table AND column_name = :column"
        ),
        {"table": table, "column": column},
    )
    return result.fetchone() is not None


def _index_exists(index_name: str) -> bool:
    """Check if an index already exists."""
    conn = op.get_bind()
    result = conn.execute(
        sa.text("SELECT 1 FROM pg_indexes WHERE indexname = :name"),
        {"name": index_name},
    )
    return result.fetchone() is not None


def upgrade() -> None:
    if not _column_exists('bills', 'public_access_token'):
        op.add_column('bills', sa.Column('public_access_token', sa.Uuid(), nullable=True))
        op.execute("UPDATE bills SET public_access_token = gen_random_uuid() WHERE public_access_token IS NULL")
    if not _index_exists('ix_bills_public_access_token'):
        op.create_index(op.f('ix_bills_public_access_token'), 'bills', ['public_access_token'], unique=True)

    if not _column_exists('products', 'type'):
        op.add_column('products', sa.Column('type', sa.String(length=50), nullable=True))
    if not _column_exists('products', 'quantity_in_stock'):
        op.add_column('products', sa.Column('quantity_in_stock', sa.Numeric(precision=15, scale=2), nullable=True))
    if not _column_exists('products', 'deleted_at'):
        op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    if not _column_exists('products', 'created_by'):
        op.add_column('products', sa.Column('created_by', sa.Uuid(), nullable=True))
    if not _column_exists('products', 'updated_by'):
        op.add_column('products', sa.Column('updated_by', sa.Uuid(), nullable=True))
    if not _column_exists('products', 'is_deleted'):
        op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # Drop indexes only if they still exist
    if _index_exists('ix_products_company_id'):
        op.drop_index(op.f('ix_products_company_id'), table_name='products')
    if _index_exists('ix_products_id'):
        op.drop_index(op.f('ix_products_id'), table_name='products')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.drop_column('products', 'is_deleted')
    op.drop_column('products', 'updated_by')
    op.drop_column('products', 'created_by')
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'quantity_in_stock')
    op.drop_column('products', 'type')
    op.drop_index(op.f('ix_bills_public_access_token'), table_name='bills')
    op.drop_column('bills', 'public_access_token')
    # ### end Alembic commands ###

