"""add_credit_period_and_gst_bifurcation

Revision ID: 311fee47621f
Revises: 8a5f52563210
Create Date: 2026-07-09 12:36:37.817372

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '311fee47621f'
down_revision: str | None = '8a5f52563210'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_items', sa.Column('cgst_amount', sa.Numeric(precision=15, scale=2), server_default='0.0', nullable=False))
    op.add_column('bill_items', sa.Column('sgst_amount', sa.Numeric(precision=15, scale=2), server_default='0.0', nullable=False))
    op.add_column('bill_items', sa.Column('igst_amount', sa.Numeric(precision=15, scale=2), server_default='0.0', nullable=False))
    op.add_column('bills', sa.Column('drawer_state', sa.String(length=100), nullable=True))
    op.add_column('bills', sa.Column('drawee_state', sa.String(length=100), nullable=True))
    op.add_column('bills', sa.Column('credit_period_months', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'credit_period_months')
    op.drop_column('bills', 'drawee_state')
    op.drop_column('bills', 'drawer_state')
    op.drop_column('bill_items', 'igst_amount')
    op.drop_column('bill_items', 'sgst_amount')
    op.drop_column('bill_items', 'cgst_amount')
    # ### end Alembic commands ###
