"""add BOE bids and draft status

Revision ID: 56b9edb77e23
Revises: fb34ade083d9
Create Date: 2026-07-19 11:05:54.857405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b9edb77e23'
down_revision: Union[str, None] = 'fb34ade083d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boe_bids',
    sa.Column('bill_of_exchange_id', sa.Uuid(), nullable=False),
    sa.Column('financier_company_id', sa.Uuid(), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bill_of_exchange_id'], ['bills_of_exchange.id'], name=op.f('fk_boe_bids_bill_of_exchange_id_bills_of_exchange')),
    sa.ForeignKeyConstraint(['financier_company_id'], ['companies.id'], name=op.f('fk_boe_bids_financier_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boe_bids'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boe_bids')
    # ### end Alembic commands ###
