"""add boe holder and negotiability

Revision ID: 65eebd6fcf3e
Revises: 56b9edb77e23
Create Date: 2026-07-19 11:16:07.978526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65eebd6fcf3e'
down_revision: Union[str, None] = '56b9edb77e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills_of_exchange', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bills_of_exchange', sa.Column('rejected_reason', sa.Text(), nullable=True))
    op.add_column('bills_of_exchange', sa.Column('current_holder_company_id', sa.Uuid(), nullable=True))
    op.add_column('bills_of_exchange', sa.Column('is_negotiable', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('bills_of_exchange', sa.Column('endorsement_restricted', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key(op.f('fk_bills_of_exchange_current_holder_company_id_companies'), 'bills_of_exchange', 'companies', ['current_holder_company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bills_of_exchange_current_holder_company_id_companies'), 'bills_of_exchange', type_='foreignkey')
    op.drop_column('bills_of_exchange', 'endorsement_restricted')
    op.drop_column('bills_of_exchange', 'is_negotiable')
    op.drop_column('bills_of_exchange', 'current_holder_company_id')
    op.drop_column('bills_of_exchange', 'rejected_reason')
    op.drop_column('bills_of_exchange', 'rejected_at')
    # ### end Alembic commands ###
