"""Remove customer_type

Revision ID: 8df2d3de45d6
Revises: be897eac254d
Create Date: 2026-07-20 12:02:36.681244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df2d3de45d6'
down_revision: Union[str, None] = 'be897eac254d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'customer_type')
    op.add_column('discounting_bids', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('discounting_bids', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('discounting_bids', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.add_column('discounting_bids', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('discounting_transactions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('discounting_transactions', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('discounting_transactions', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.add_column('discounting_transactions', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discounting_transactions', 'is_deleted')
    op.drop_column('discounting_transactions', 'updated_by')
    op.drop_column('discounting_transactions', 'created_by')
    op.drop_column('discounting_transactions', 'deleted_at')
    op.drop_column('discounting_bids', 'is_deleted')
    op.drop_column('discounting_bids', 'updated_by')
    op.drop_column('discounting_bids', 'created_by')
    op.drop_column('discounting_bids', 'deleted_at')
    op.add_column('customers', sa.Column('customer_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
