"""add_transaction_type

Revision ID: af39c5170d0f
Revises: 311fee47621f
Create Date: 2026-07-09 13:04:11.548894

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'af39c5170d0f'
down_revision: str | None = '311fee47621f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('transaction_type', sa.String(length=50), server_default='intra_state', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'transaction_type')
    # ### end Alembic commands ###
