"""add financier profiles and discounting requests

Revision ID: af753798f338
Revises: c1fd3a8f1e5b
Create Date: 2026-07-19 11:34:32.691116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af753798f338'
down_revision: Union[str, None] = 'c1fd3a8f1e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounting_requests',
    sa.Column('bill_of_exchange_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_company_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tenor_days', sa.Integer(), nullable=False),
    sa.Column('bidding_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bidding_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('min_acceptable_rate_bps', sa.Integer(), nullable=True),
    sa.Column('max_acceptable_rate_bps', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('selected_bid_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bill_of_exchange_id'], ['bills_of_exchange.id'], name=op.f('fk_discounting_requests_bill_of_exchange_id_bills_of_exchange')),
    sa.ForeignKeyConstraint(['requested_by_company_id'], ['companies.id'], name=op.f('fk_discounting_requests_requested_by_company_id_companies')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_discounting_requests_requested_by_user_id_users')),
    sa.ForeignKeyConstraint(['selected_bid_id'], ['boe_bids.id'], name=op.f('fk_discounting_requests_selected_bid_id_boe_bids')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discounting_requests'))
    )
    op.create_index(op.f('ix_discounting_requests_bill_of_exchange_id'), 'discounting_requests', ['bill_of_exchange_id'], unique=False)
    op.create_table('financier_profiles',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('license_type', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('min_rate_bps', sa.Integer(), nullable=False),
    sa.Column('max_exposure_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('settlement_bank_account_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_financier_profiles_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financier_profiles'))
    )
    op.create_index(op.f('ix_financier_profiles_company_id'), 'financier_profiles', ['company_id'], unique=True)
    op.add_column('boe_bids', sa.Column('discounting_request_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_boe_bids_discounting_request_id_discounting_requests'), 'boe_bids', 'discounting_requests', ['discounting_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_boe_bids_discounting_request_id_discounting_requests'), 'boe_bids', type_='foreignkey')
    op.drop_column('boe_bids', 'discounting_request_id')
    op.drop_index(op.f('ix_financier_profiles_company_id'), table_name='financier_profiles')
    op.drop_table('financier_profiles')
    op.drop_index(op.f('ix_discounting_requests_bill_of_exchange_id'), table_name='discounting_requests')
    op.drop_table('discounting_requests')
    # ### end Alembic commands ###
