"""update boe endorsements table

Revision ID: c1fd3a8f1e5b
Revises: 65eebd6fcf3e
Create Date: 2026-07-19 11:28:48.874504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1fd3a8f1e5b'
down_revision: Union[str, None] = '65eebd6fcf3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boe_endorsements', sa.Column('sequence_no', sa.Integer(), nullable=False))
    op.add_column('boe_endorsements', sa.Column('endorser_name', sa.String(length=255), nullable=False))
    op.add_column('boe_endorsements', sa.Column('endorser_signature_ref', sa.Uuid(), nullable=True))
    op.add_column('boe_endorsements', sa.Column('endorsee_name', sa.String(length=255), nullable=False))
    op.add_column('boe_endorsements', sa.Column('endorsee_address', sa.Text(), nullable=True))
    op.add_column('boe_endorsements', sa.Column('endorsee_phone', sa.String(length=50), nullable=True))
    op.add_column('boe_endorsements', sa.Column('endorsee_email', sa.String(length=255), nullable=True))
    op.add_column('boe_endorsements', sa.Column('endorsement_type', sa.String(length=50), nullable=False))
    op.add_column('boe_endorsements', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('boe_endorsements', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('boe_endorsements', 'endorsee_company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('boe_endorsements', 'endorsement_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_boe_endorsements_endorser_signature_ref_documents'), 'boe_endorsements', 'documents', ['endorser_signature_ref'], ['id'])
    op.drop_column('boe_endorsements', 'notes')
    op.drop_column('boe_endorsements', 'status')
    op.drop_column('boe_endorsements', 'amount')
    op.drop_column('boe_endorsements', 'discount_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boe_endorsements', sa.Column('discount_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('boe_endorsements', sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('boe_endorsements', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('boe_endorsements', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_boe_endorsements_endorser_signature_ref_documents'), 'boe_endorsements', type_='foreignkey')
    op.alter_column('boe_endorsements', 'endorsement_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('boe_endorsements', 'endorsee_company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('boe_endorsements', 'is_active')
    op.drop_column('boe_endorsements', 'remarks')
    op.drop_column('boe_endorsements', 'endorsement_type')
    op.drop_column('boe_endorsements', 'endorsee_email')
    op.drop_column('boe_endorsements', 'endorsee_phone')
    op.drop_column('boe_endorsements', 'endorsee_address')
    op.drop_column('boe_endorsements', 'endorsee_name')
    op.drop_column('boe_endorsements', 'endorser_signature_ref')
    op.drop_column('boe_endorsements', 'endorser_name')
    op.drop_column('boe_endorsements', 'sequence_no')
    # ### end Alembic commands ###
