"""Add network sync columns to bills

Revision ID: c201e8df15c9
Revises: f753cde62609
Create Date: 2026-07-10 11:56:55.789851

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c201e8df15c9'
down_revision: str | None = 'f753cde62609'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('network_drawee_company_id', sa.Uuid(), nullable=True))
    op.add_column('bills', sa.Column('network_payee_company_id', sa.Uuid(), nullable=True))
    op.add_column('bills', sa.Column('drawee_creditor_id', sa.Uuid(), nullable=True))
    op.add_column('bills', sa.Column('payee_customer_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_bills_network_drawee_company_id_companies'), 'bills', 'companies', ['network_drawee_company_id'], ['id'])
    op.create_foreign_key(op.f('fk_bills_drawee_creditor_id_creditors'), 'bills', 'creditors', ['drawee_creditor_id'], ['id'])
    op.create_foreign_key(op.f('fk_bills_payee_customer_id_customers'), 'bills', 'customers', ['payee_customer_id'], ['id'])
    op.create_foreign_key(op.f('fk_bills_network_payee_company_id_companies'), 'bills', 'companies', ['network_payee_company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bills_network_payee_company_id_companies'), 'bills', type_='foreignkey')
    op.drop_constraint(op.f('fk_bills_payee_customer_id_customers'), 'bills', type_='foreignkey')
    op.drop_constraint(op.f('fk_bills_drawee_creditor_id_creditors'), 'bills', type_='foreignkey')
    op.drop_constraint(op.f('fk_bills_network_drawee_company_id_companies'), 'bills', type_='foreignkey')
    op.drop_column('bills', 'payee_customer_id')
    op.drop_column('bills', 'drawee_creditor_id')
    op.drop_column('bills', 'network_payee_company_id')
    op.drop_column('bills', 'network_drawee_company_id')
    # ### end Alembic commands ###
