"""make company email and phone mandatory

Revision ID: f753cde62609
Revises: af39c5170d0f
Create Date: 2026-07-10 10:46:24.754054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f753cde62609'
down_revision: Union[str, None] = 'af39c5170d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Set default values for existing rows to prevent NOT NULL constraint violations
    op.execute("UPDATE companies SET email = 'default@example.com' WHERE email IS NULL")
    op.execute("UPDATE companies SET phone = '0000000000' WHERE phone IS NULL")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('companies', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('companies', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
