"""Add company_type and TReDS BOE models

Revision ID: fb34ade083d9
Revises: add_network_drawee_boe
Create Date: 2026-07-19 10:47:39.070310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb34ade083d9'
down_revision: Union[str, None] = 'add_network_drawee_boe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boe_endorsements',
    sa.Column('bill_of_exchange_id', sa.Uuid(), nullable=False),
    sa.Column('endorser_company_id', sa.Uuid(), nullable=False),
    sa.Column('endorsee_company_id', sa.Uuid(), nullable=False),
    sa.Column('endorsement_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endorsed_by', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bill_of_exchange_id'], ['bills_of_exchange.id'], name=op.f('fk_boe_endorsements_bill_of_exchange_id_bills_of_exchange')),
    sa.ForeignKeyConstraint(['endorsed_by'], ['users.id'], name=op.f('fk_boe_endorsements_endorsed_by_users')),
    sa.ForeignKeyConstraint(['endorsee_company_id'], ['companies.id'], name=op.f('fk_boe_endorsements_endorsee_company_id_companies')),
    sa.ForeignKeyConstraint(['endorser_company_id'], ['companies.id'], name=op.f('fk_boe_endorsements_endorser_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boe_endorsements'))
    )
    op.create_table('boe_status_history',
    sa.Column('bill_of_exchange_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=False),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bill_of_exchange_id'], ['bills_of_exchange.id'], name=op.f('fk_boe_status_history_bill_of_exchange_id_bills_of_exchange')),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_boe_status_history_changed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_boe_status_history'))
    )
    op.add_column('bills_of_exchange', sa.Column('public_access_token', sa.Uuid(), nullable=True))
    op.add_column('bills_of_exchange', sa.Column('endorsee_company_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_bills_of_exchange_public_access_token'), 'bills_of_exchange', ['public_access_token'], unique=True)
    op.create_foreign_key(op.f('fk_bills_of_exchange_endorsee_company_id_companies'), 'bills_of_exchange', 'companies', ['endorsee_company_id'], ['id'])
    op.add_column('companies', sa.Column('company_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'company_type')
    op.drop_constraint(op.f('fk_bills_of_exchange_endorsee_company_id_companies'), 'bills_of_exchange', type_='foreignkey')
    op.drop_index(op.f('ix_bills_of_exchange_public_access_token'), table_name='bills_of_exchange')
    op.drop_column('bills_of_exchange', 'endorsee_company_id')
    op.drop_column('bills_of_exchange', 'public_access_token')
    op.drop_table('boe_status_history')
    op.drop_table('boe_endorsements')
    # ### end Alembic commands ###
